### ISSUE TITLE
Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral

### ISSUE THREAD

**Issue by AhmedElbaik** [JoshKeegan/xRetry#252] opened 2024-10-20 22:20 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB4018	The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at xRetry.Reqnroll.GeneratorPlugin.customiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPluginInfos, IObjectContainer parentObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection`1 generatorPluginInfos, IObjectContainer rootObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute()
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	CostbookUITestsBDD	C:\Users\elbaika\.nuget\packages\reqnroll.tools.msbuild.generation\2.1.1\build\Reqnroll.Tools.MsBuild.Generation.targets	93	
	
I'm facing the above error. I checked https://github.com/reqnroll/Reqnroll/issues/244 and #245, which should fix the problem.
as you can see below the versions of the packages I have:-
"Reqnroll" Version="2.1.1"
"Reqnroll.CustomPlugin" Version="2.1.1" 
"Reqnroll.Autofac" Version="2.1.1"
"Reqnroll.SpecFlowCompatibility" Version="2.1.1"
"Reqnroll.Tools.MsBuild.Generation" Version="2.1.1"
"Reqnroll.xUnit" Version="2.1.1"
"xRetry.Reqnroll" Version="1.0.0"
System.CodeDom" Version="8.0.0"

I would appreciate your help with how to fix this issue.

**Comment by JoshKeegan** [comment] 2024-10-21 18:35
Hi, does it work if you downgrade all of the Reqnroll packages to 2.0.0?

**Comment by AhmedElbaik** [comment] 2024-10-21 23:22
It seems to be working now. One note I have is that adding the @retry above feature won't retry the scenarios in this feature file.
about this issue, is it something will be fixed in xRetry.Reqnroll Release or should I mention the issue in Reqnroll Repo so they fix it in upcoming releases?

**Comment by JoshKeegan** [comment] 2024-10-22 17:54
Do you mean it works after downgrading Reqnroll to 2.0.0? If so, it's likely an issue with Reqnroll, so it'd be worth raising in their repo. I thought they'd fixed this error in https://github.com/reqnroll/Reqnroll/pull/245 though 🤔 

Since you're saying that adding `@retry` isn't working, something still seems wrong though. Are you able to share your project, or a minimal project to reproduce the issue?

**Comment by AhmedElbaik** [comment] 2024-10-23 21:44
unfortunately, I'm not able to share my project.
Yes, it worked after downgrading to 2.0.0 when adding @retry above the scenario. However, it was not working when adding it above the Feature, but now it seems to be working there, too!
in conclusion Reqnroll 2.0.0 and xRetry.Reqnroll 1.0.0 are working fine together. 
Thanks for the advice I will raise this issue again in Reqnroll repo issues.

**Comment by gasparnagy** [comment] 2024-11-05 15:56
I have analyzed the problem on Reqnroll side. The direct problem could be fixed by the change @JoshKeegan did here, but it turned out to be a more generic issue with Reqnroll. A similar problem would happen time to time (Reqnroll v2.2 will have a dependency update on the Gherkin package that would cause a similar issue.)

The good news is that I have found a fix: https://github.com/reqnroll/Reqnroll/pull/316

Also as part of the fix I have added a test that checks the compatibility with this plugin, so hopefully we will not have such issues.

I plan to release the fix as part of Reqnroll v2.2.0 this week. That will work with xRetry.Reqnroll 1.0.0 as well.

**Comment by JoshKeegan** [comment] 2024-11-05 17:37
Thanks for investigating @gasparnagy! Your fix sounds sensible since it makes .Net Framework MSBuild match the out-of-the-box behaviour of dotnet build :+1: 

I've re-opened this issue & will leave it open until Reqnroll v2.2.0 is released with the fix, in case anyone else comes across this.

For anyone else that comes across this trying to use xRetry.Reqnroll, the summary is: if you're using `dotnet build` you're safe, but if using MSBuild stick with Reqnroll v2.0.0 until v2.2.0 is released.

**Comment by JoshKeegan** [comment] 2024-11-08 18:34
With Reqnroll v2.2.0 now released, I'm going to close this.

**Closed by JoshKeegan** 2024-11-08 18:34 UTC
