### ISSUE TITLE
 Retry does not work with Xunit.DependencyInjection

### ISSUE THREAD

**Issue by ildar-shamilov-clearscale** [JoshKeegan/xRetry#131] opened 2022-03-14 16:43 UTC
I have reference to  Xunit.DependencyInjection version in my project "8.3.0".
After hours of struggling to get Retry work - i removed this package from test project and got it work.

Is it possible to fix? Any workaround? Maybe update documentation that this libs are incompatible?

Thank you.

**Comment by JoshKeegan** [comment] 2022-03-14 17:40
Hi, 
Sorry to hear you've had problems with getting these libraries to work together. Generally xRetry should work alongside other xunit plugins because we're adding new attributes (`RetryFact` and `RetryTheory`) rather than modifying the behaviour of the built-in ones and xunit is designed to be extensible in this way. 

I've had a quick look at Xunit.DependencyInjection and it looks like it needs to modify the test discovery process which is likely what is causing this issue. e.g. it may only be looking for `FactAttribute` rathern than for any attribute that has an `XunitTestCaseDiscoverer` attribute itself, which would prevent it from picking up the `RetryFact`. Are you able to raise the issue with Xunit.DependencyInjection? Someone familiar with that codebase should be able to explain whether this incompatibility is by design or a bug.

**Comment by JoshKeegan** [comment] 2022-05-20 16:44
Any update on this @ildar-shamilov-clearscale?

**Comment by JoshKeegan** [comment] 2022-12-19 19:13
Will require a new package in Xunit.DependencyInjection that integrates with xRetry. Have started work on this [here](https://github.com/JoshKeegan/Xunit.DependencyInjection/tree/xRetry).

Basic functionality is working, retry theory with non-serializable test data needs doing (failing test case added).

**Comment by pengweiqhca** [comment] 2022-12-23 01:29
https://www.nuget.org/packages/Xunit.DependencyInjection.xRetry/

**Comment by JoshKeegan** [comment] 2023-01-01 20:39
I've tested the pre-release packages together and it's all working fine 👍. Thanks for releasing it so quickly @pengweiqhca.

xRetry v1.9 is now released, and the PR to make Xunit.DependencyInjection.xRetry not prerelease any more is raised: https://github.com/pengweiqhca/Xunit.DependencyInjection/pull/77 so I'll close this.

@ildar-shamilov-clearscale please let us know how you get on using these together and re-open this if you still have problems.

**Closed by JoshKeegan** 2023-01-01 20:39 UTC
Labels: third_party

**Comment by pengweiqhca** [comment] 2023-01-02 10:09
[Xunit.DependencyInjection.xRetry 8.0.0](https://www.nuget.org/packages/Xunit.DependencyInjection.xRetry/8.0.0) is released.
